os: linux
dist: bionic
sudo: required

language:
  - cpp
  - c
compiler:
  - gcc
  - g++
  

      
before_script:
  - sudo apt-get update
  - sudo apt-get install gcc --only-upgrade
  - sudo apt-get install g++ --only-upgrade
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build

script:
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - cmake ..
  - make
