os: linux
dist: bionic
sudo: required

language:
  - cpp
  - c
compiler:
  - gcc
  - g++
  
addons:
  apt:
    packages:
      - python-yaml
      - lcov
      - libopencv-dev
    sources:
      - ubuntu-toolchain-r-test


before_script:
  - sudo pip install codecov
  #- sudo apt-get update
  #- sudo apt-get install gcc --only-upgrade
  #- sudo apt-get install g++ --only-upgrade
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build

script:
  # Run your build commands
  - cmake ..
  - make

after_success:
    - codecov -t 85d17b4e-7469-40be-927a-004fc813c966 -X gcov
    - bash <(curl -s https://codecov.io/bash)
