dist: trusty
sudo: required
language:
  - cpp
  - c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - g++
      - cmake
      
before_script:
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build

script:
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - cmake ..
  - make
